### PR TITLE
Fix issue where LinkKit version getting out of sync with the bridge c…

### LINKED ISSUE #343: App is crashing on clicking on continue button on  success plaid screen
# The problem

I just updated react-native-plaid-link-sdk to v7.0.0 and the app is crashing on clicking on the continue button on the success plaid screen.

# Environment

|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | v7.0.0                |
| ReactNative Version     | v0.63.2                |
| iOS Devices/Emulators               | iPhone 12               |
| Plaid               | v2.0.11             |

# Steps to Reproduce
- Enter user details and click next.
- Account gets linked successfully.
- Click on the continue button and the app crashes.

# Error

Getting this error on the Xcode console output.
```
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003475e50 UIButtonLabel:0x7fcbca8c7860.centerY == _UIModernBarButton:0x7fcbca8c5a30'Done'.centerY + 1.5   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2021-03-17 18:54:01.349480+0530 Line[47888:320060] -[PLKSuccessMetadata institution]: unrecognized selector sent to instance 0x6000018a5d40
2021-03-17 18:54:01.360846+0530 Line[47888:320060] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PLKSuccessMetadata institution]: unrecognized selector sent to instance 0x6000018a5d40'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204306f7 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x00007fff20426036 ___forwarding___ + 1489
	4   CoreFoundation                      0x00007fff20428068 _CF_forwarding_prep_0 + 120
	5   Line                                0x000000010376731c +[RNLinksdk dictionaryFromSuccess:] + 428
	6   Line                                0x0000000103762b07 __20-[RNLinksdk create:]_block_invoke + 263
	7   LinkKit                             0x000000010f2ebc1c block_destroy_helper.8 + 19468
	8   LinkKit                             0x000000010f2dc915 globalinit_33_3539F515EB857A77839ECAB662545DDA_func120 + 12181
	9   LinkKit                             0x000000010f2acbde __swift_project_boxed_opaque_existential_1 + 3118
	10  libdispatch.dylib                   0x000000010fecc7ec _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010fecd9c8 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010fedbe75 _dispatch_main_queue_callback_4CF + 1152
	13  CoreFoundation                      0x00007fff2038fdbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x00007fff2038a63e __CFRunLoopRun + 2685
	15  CoreFoundation                      0x00007fff203896d6 CFRunLoopRunSpecific + 567
	16  GraphicsServices                    0x00007fff2c257db3 GSEventRunModal + 139
	17  UIKitCore                           0x00007fff24696cf7 -[UIApplication _run] + 912
	18  UIKitCore                           0x00007fff2469bba8 UIApplicationMain + 101
	19  Line                                0x0000000102ef59b0 main + 112
	20  libdyld.dylib                       0x00007fff2025a3e9 start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PLKSuccessMetadata institution]: unrecognized selector sent to instance 0x6000018a5d40'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 (B681C767-9B56-40BA-9BFC-A46D022E610D) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12
```

<details><summary>Screenshot of success screen</summary>

</details>

### PR DESCRIPTION
**Pull request by pladaub**
…aused a crash

LinkKit v2 launched with a typo in PLKSuccessMetadata. The typo was addressed in v2.0.11, and subsequently react-native-plaid-link-sdk v7 specified a minimum LinkKit dependency of v2.0.11. This should mean that all RN versions prior to 7 have the typo, and rely on a LinkKit version that also has the typo whereas all RN versions 7 or newer should not have the typo, and should rely on a LinkKit version that also does not have the typo.

Despite this being theoretically safe, #343 shows a crash where the RN version (7+) uses the corrected spelling, but LinkKit does not have that selector. I am not sure how this can happen in practice, my best guess is something weird is going on with Cocoapods' dependency resolution.

This PR addresses the issue by having the bridge first check for the existence of the correct selector, and then the existence of the old selector, before finally failing with an assertion (that will be stripped from production builds) if neither is implemented.

Closes #343

### CODE REVIEW

**Comment by afh** [comment]
@pladaub What are your thoughts on tucking the handling of `institution` and `insitution` away in the following, which adds the implementation of `insitution` to `PLKSuccessMetadata` with the name `institution`, so that the existing `dictionaryFromSuccess:` can be left unchanged ?

```
#import <objc/runtime.h>
// …
@implementation RNLinksdk
// …
+ (void)load {
    SEL typoSel = NSSelectorFromString(@"insitution");
    SEL correctSel = NSSelectorFromString(@"institution");
    Class successMetaDataClass = [PLKSuccessMetadata class];
    if (class_respondsToSelector(successMetaDataClass, typoSel)
        && !class_respondsToSelector(successMetaDataClass, correctSel)) {
        Method method = class_getInstanceMethod(successMetaDataClass, typoSel);
        const char* types = method_getTypeEncoding(method);
        IMP implementation = class_getMethodImplementation(successMetaDataClass, typoSel);
        class_addMethod(successMetaDataClass, correctSel, implementation, types);
    }
}
// …
```

**Comment by pladaub** [comment]
> @pladaub What are your thoughts on tucking the handling of `institution` and `insitution` away in the following, which adds the implementation of `insitution` to `PLKSuccessMetadata` with the name `institution`, so that the existing `dictionaryFromSuccess:` can be left unchanged ?
> 
> ```
> #import <objc/runtime.h>
> // …
> @implementation RNLinksdk
> // …
> + (void)load {
>     SEL typoSel = NSSelectorFromString(@"insitution");
>     SEL correctSel = NSSelectorFromString(@"institution");
>     Class successMetaDataClass = [PLKSuccessMetadata class];
>     if (class_respondsToSelector(successMetaDataClass, typoSel)
>         && !class_respondsToSelector(successMetaDataClass, correctSel)) {
>         Method method = class_getInstanceMethod(successMetaDataClass, typoSel);
>         const char* types = method_getTypeEncoding(method);
>         IMP implementation = class_getMethodImplementation(successMetaDataClass, typoSel);
>         class_addMethod(successMetaDataClass, correctSel, implementation, types);
>     }
> }
> // …
> ```

My initial reaction is I would prefer to avoid messing with the runtime where possible, but I do like that this fixes any usage of `-[PLKSuccessMetadata institution]` whereas the current fix only addresses `dictionaryFromSuccess:`.

Don't feel super strongly either way, but if we take this approach I would at least like to add the assert if it doesn't respond to either selector

**Comment by afh** [comment]
Agree on being careful when dropping down to the Objective-C runtime, @pladaub, yet fixing the issue more wholesome seems a worthwhile benefit. I like the suggestion of adding an assert in case neither selector is present.

File: ios/RNLinksdk.m [hunk 1]
```diff
@@ -48,6 +50,42 @@ @interface RNLinksdk ()
...
+
+@implementation PLKSuccessMetadataTypoFix
+
++ (void)load {
+    Class targetClass = NSClassFromString(@"PLKSuccessMetadata");
+    SEL typoSel = NSSelectorFromString(@"insitution");
+    SEL correctSel = NSSelectorFromString(@"institution");
+
+    BOOL respondsToCorrectSel = class_respondsToSelector(targetClass, correctSel);
+    BOOL respondsToTypoSel = class_respondsToSelector(targetClass, typoSel);
```
Comment (amytang0) [inline ios/RNLinksdk.m:65]:
```suggestion
    BOOL respondsToTypoSel = class_respondsToSelector(targetClass, typoSel);
    BOOL respondsToCorrectSel = class_respondsToSelector(targetClass, correctSel);
```

nit: Keep ordering consistent

File: ios/RNLinksdk.m [hunk 2]
```diff
@@ -48,6 +50,42 @@ @interface RNLinksdk ()
...
+
+    if (respondsToCorrectSel && respondsToTypoSel) {
+        return;
+    }
+
```
Comment (amytang0) [inline ios/RNLinksdk.m:70]: Suggestion to clarify the next bits by using a helper variable `missingSel` and `existingSel`:
```
  if (!respondsToCorrectSel && !respondsToTypoSel) {
        // throw the github issues error
    }
    
SEL missingSel = (respondsToTypoSel) ? correctSel : typoSel
SEL existingSel = (respondsToTypoSel) ? typoSel : correctSel 

```

Helps with the DRY

**Review by amytang0 — COMMENTED** [review]
TIL some Obj C magic

LGTM, but gonna let Alexis look over the Obj C for final LGTM

File: ios/RNLinksdk.m (hunk 2 above)
Comment (afh) [reply ios/RNLinksdk.m:70]: @pladaub I really like @amytang0's suggestion as it makes the change much more readable and should allow to shorten the code to:

```
+ (void)load {
    Class targetClass = NSClassFromString(@"PLKSuccessMetadata");
    SEL typoSel = NSSelectorFromString(@"insitution");
    SEL correctSel = NSSelectorFromString(@"institution");

    BOOL respondsToTypoSel = class_respondsToSelector(targetClass, typoSel);
    BOOL respondsToCorrectSel = class_respondsToSelector(targetClass, correctSel);

    if (!(respondsToCorrectSel || respondsToTypoSel)) {
        NSString *githubIssueURLString = @"https://github.com/plaid/react-native-plaid-link-sdk/issues/new?assignees=&labels=&template=bug_report.md&title=";
        NSAssert(false, @"PLKSuccessMetadata does not respond to correctly spelled %@ or legacy, typo %@. This is a bug in either react-native-plaid-link-sdk, or LinkKit. Please file an issue at: %@", NSStringFromSelector(correctSel), NSStringFromSelector(typoSel), githubIssueURLString);
    }

    SEL missingSel = (respondsToTypoSel) ? correctSel : typoSel;
    SEL existingSel = (respondsToTypoSel) ? typoSel : correctSel;
    Method method = class_getInstanceMethod(targetClass, existingSel);
    const char* types = method_getTypeEncoding(method);
    IMP implementation = class_getMethodImplementation(targetClass, existingSel);
    class_addMethod(targetClass, missingSel, implementation, types);
}
```

**Review by afh — APPROVED** [review]
Approving after considering @amytang0's suggestion and my comment below.

File: ios/RNLinksdk.m (hunk 2 above)
Comment (pladaub) [reply ios/RNLinksdk.m:70]: Yes, very much like this. We still need to check that swizzling isn't necessary, but this is a big readability improvement.

File: ios/RNLinksdk.m [hunk 3]
```diff
@@ -48,6 +50,62 @@ @interface RNLinksdk ()
...
+@end
+
+@implementation PLKSuccessMetadataTypoFix
+
++ (void)load {
+    static dispatch_once_t onceToken;
+    // dispatch_once out of an abundance of caution in case +load is ever called multiple times
+    dispatch_once(&onceToken, ^{
+        Class targetClass = NSClassFromString(@"PLKSuccessMetadata");
```
Comment (afh) [inline ios/RNLinksdk.m:75]: I think it would be benefical to assert `targetClass != Nil` (yes [`Nil`](https://nshipster.com/nil/)) and exit early if the precondition isn't met.

File: ios/RNLinksdk.m [hunk 4]
```diff
@@ -48,6 +50,62 @@ @interface RNLinksdk ()
...
+        // If PLKSuccessMetadata responds to both, no swizzling is necessary
+        if (respondsToBoth) {
+            return;
+        }
+
+        BOOL respondsToNeither = !(respondsToCorrectSel || respondsToTypoSel);
+        // If PLKSuccessMetadata responds to neither, swizzling cannot fix this
+        if (respondsToNeither) {
+            NSString *githubIssueURLString = @"https://github.com/plaid/react-native-plaid-link-sdk/issues/new?assignees=&labels=&template=bug_report.md&title=";
+            NSAssert(false, @"PLKSuccessMetadata does not respond to correctly spelled %@ or legacy, typo %@. This is a bug in either react-native-plaid-link-sdk, or LinkKit. Please file an issue at: %@", NSStringFromSelector(correctSel), NSStringFromSelector(typoSel), githubIssueURLString);
```
Comment (afh) [inline ios/RNLinksdk.m:93]: nit: Use `targetClass` in the assert message.
```suggestion
            NSAssert(false, @"%@ does not respond to correctly spelled %@ or legacy, typo %@. This is a bug in either react-native-plaid-link-sdk, or LinkKit. Please file an issue at: %@", NSStringFromClass(targetClass), NSStringFromSelector(correctSel), NSStringFromSelector(typoSel), githubIssueURLString);
```

**Review by afh — APPROVED** [review]
Great improvements, @pladaub. 

I think we can go above and beyond and assert that `targetClass` exists in early exit if it does not (see comment below).
