### PR TITLE
(Change base branch to main once bridgePublicTokens lands) – Ensure the dismissal logic is only invoked once

### LINKED ISSUE #227: iOS - When Plaid closes, it closes all other modals and leaves app in unresponsive state
# The problem
If a react-native Modal is open when Plaid exits (e.g. Plaid is launched from a Modal), Plaid closes that modal, and the app is no longer responsive.

# Environment
|                        |  |
| ------------------------| ---------- |
| Plaid Link React Native          | 6.0.2                |
| ReactNative Version     | 0.63.3 (also seen in 61.5)                |
| Occurs on Android             | no                |
| Android OS Version                    |                 |
| Android Devices/Emulators    |                 |
| Occurs on iOS     | yes                |
| iOS Version           | 13.5 (also seen in 11)                |
| iOS Devices/Emulators               | iPhone 11 Simulator                |

# Steps to Reproduce
1. Add a PlaidLink button to a react-native Modal
2. Open the modal, then launch Plaid
3. Exit Plaid
4. Observe the modal is also closed and the app is no longer responsive

# Expected Result
Plaid should not close other modals nor leave the app in an unresponsive state.

# Screenshots
https://i.imgur.com/i01qB0v.mp4

# Logs
This probably isn't relevant, but I'll include it just in case. This is what I see in the logs when I trigger the bug.

```
2020-10-20 16:29:40.319389-0400 PlaidModalBug[12476:106719] WF: _userSettingsForUser : (null)
2020-10-20 16:29:40.319559-0400 PlaidModalBug[12476:106719] WF: _WebFilterIsActive returning: NO
2020-10-20 16:29:40.579252-0400 PlaidModalBug[12476:106719] Unbalanced calls to begin/end appearance transitions for <LinkKit.InProcessWebviewFallbackController: 0x7fe416f29d80>.
2020-10-20 16:29:44.332931-0400 PlaidModalBug[12476:106719] [ProcessSuspension] 0x117e26b10 - ProcessAssertion::processAssertionWasInvalidated()
2020-10-20 16:29:44.338826-0400 PlaidModalBug[12476:106719] [ProcessSuspension] 0x117e26ab0 - ProcessAssertion::processAssertionWasInvalidated()
```

# Code To Reproduce Issue 
Here's a repo demonstrating the faulty behavior. Make sure to replace the `client_id` and `secret`. https://github.com/bpander/PlaidModalBug

### PR DESCRIPTION
**Pull request by pladaub**
Using the new dismissalHandler API, we can keep the existing cleanup code in -dismiss while preventing another call to dismissing the view controller from being initiated by LinkKit.

Closes #227

### CODE REVIEW

File: ios/RNLinksdk.m [hunk 1]
```diff
@@ -237,7 +235,15 @@ - (void)stopObserving {
...
         self.presentingViewController = RCTPresentedViewController();
         NSDictionary *options = self.institutionID.length > 0 ? @{@"institution_id": self.institutionID} : @{};
-        [self.linkHandler openWithContextViewController:self.presentingViewController options:options];
+
+        __weak typeof(self) weakSelf = self;
+        void(^presentationHandler)(UIViewController *) = ^(UIViewController *linkViewController) {
+            [weakSelf.presentingViewController presentViewController:linkViewController animated:true completion:nil];
+        };
+        void(^dismissalHandler)(UIViewController *) = ^(UIViewController *linkViewController) {
+            [weakSelf dismiss];
```
Comment (afh) [inline ios/RNLinksdk.m:244]: If this is an intentional code change I think the `dismissLinkViewController` method implementation can be removed. If it isn't I think `dismissLinkViewController` should be called here…
```suggestion
            [weakSelf dismissLinkViewController];
```

**Review by afh — APPROVED** [review]
LGTM after consideration of my comment about `dismiss` vs. `dismissLinkViewController`

File: ios/RNLinksdk.m (hunk 1 above)
Comment (pladaub) [reply ios/RNLinksdk.m:244]: `dismiss` is the exported API exposed by the RN layer, it exits Link and cleans up any resources (i.e. the handler and reference to the `presentedViewController`), it calls `dismissLinkViewController` in an attempt to be more readable.

On second thought though, `dismissLinkViewController` should probably never be called outside of `dismiss`, so I'll inline it to avoid the confusion
